// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHEoysqgP8kbtuQd9OHj_wyO0PJhxFUY',
    appId: '1:152008461263:android:789ab7bbe1d80b37cfa0ba',
    messagingSenderId: '152008461263',
    projectId: 'flutter-chat-5a469',
    storageBucket: 'flutter-chat-5a469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA24q_46MgHbMl3-7vJ98pHK_UkR2UkCAI',
    appId: '1:152008461263:ios:619b94b3a1ce0f3acfa0ba',
    messagingSenderId: '152008461263',
    projectId: 'flutter-chat-5a469',
    storageBucket: 'flutter-chat-5a469.appspot.com',
    androidClientId: '152008461263-gtckhoqr0tiqfggjimdgddmkqh4pnbsp.apps.googleusercontent.com',
    iosClientId: '152008461263-glithncse8p3h3tv9u8q7oo31n11bthf.apps.googleusercontent.com',
    iosBundleId: 'com.yurich.flutterchat.flutterChat',
  );
}
